set background=dark
if exists('g:colors_name')
hi clear
if exists('syntax_on')
syntax reset
endif
endif
let g:colors_name = 'lushwal'
highlight Normal guifg=#C2C4C7 guibg=#0E1420 guisp=NONE blend=NONE gui=NONE
highlight! link User Normal
highlight Bold guifg=#C2C4C7 guibg=#0E1420 guisp=NONE blend=NONE gui=bold
highlight Boolean guifg=#6A707C guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Character guifg=#5D636F guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight ColorColumn guifg=#787F8C guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Comment guifg=#C2C4C7 guibg=NONE guisp=NONE blend=NONE gui=italic
highlight Conceal guifg=#5C6370 guibg=#0E1420 guisp=NONE blend=NONE gui=NONE
highlight! link Whitespace Conceal
highlight Conditional guifg=#BFB8C1 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Constant guifg=#6A707C guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Cursor guifg=#0E1420 guibg=#C2C4C7 guisp=NONE blend=NONE gui=NONE
highlight CursorColumn guifg=#787F8C guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight CursorLine guifg=NONE guibg=#5C6370 guisp=NONE blend=NONE gui=NONE
highlight CursorLineNr guifg=#C2C4C7 guibg=#0E1420 guisp=NONE blend=NONE gui=NONE
highlight Debug guifg=#5D636F guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Define guifg=#BFB8C1 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Delimiter guifg=#616875 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight DiagnosticError guifg=#5D636F guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight DiagnosticHint guifg=#9096A2 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight DiagnosticInfo guifg=#7C828D guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight DiagnosticUnderlineError guifg=#5D636F guibg=NONE guisp=#5D636F blend=NONE gui=underline
highlight DiagnosticUnderlineHint guifg=#9096A2 guibg=NONE guisp=#9096A2 blend=NONE gui=underline
highlight DiagnosticUnderlineInfo guifg=#7C828D guibg=NONE guisp=#7C828D blend=NONE gui=underline
highlight DiagnosticUnderlineWarn guifg=#747A86 guibg=NONE guisp=#747A86 blend=NONE gui=underline
highlight DiagnosticWarn guifg=#747A86 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight DiffAdd guifg=#676D79 guibg=#5C6370 guisp=NONE blend=NONE gui=bold
highlight! link DiffAdded DiffAdd
highlight DiffChange guifg=#9EA2A9 guibg=#5C6370 guisp=NONE blend=NONE gui=NONE
highlight DiffDelete guifg=#5D636F guibg=#5C6370 guisp=NONE blend=NONE gui=bold
highlight! link DiffRemoved DiffDelete
highlight! link diffRemoved DiffDelete
highlight DiffFile guifg=#5D636F guibg=#0E1420 guisp=NONE blend=NONE gui=NONE
highlight DiffLine guifg=#7C828D guibg=#0E1420 guisp=NONE blend=NONE gui=NONE
highlight DiffNewFile guifg=#676D79 guibg=#0E1420 guisp=NONE blend=NONE gui=NONE
highlight DiffText guifg=#7C828D guibg=#5C6370 guisp=NONE blend=NONE gui=NONE
highlight Directory guifg=#7C828D guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight EndOfBuffer guifg=#C2C4C7 guibg=#0E1420 guisp=NONE blend=NONE gui=NONE
highlight Error guifg=#5D636F guibg=#C2C4C7 guisp=NONE blend=NONE gui=NONE
highlight ErrorMsg guifg=#5D636F guibg=#0E1420 guisp=NONE blend=NONE gui=NONE
highlight Exception guifg=#5D636F guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Float guifg=#6A707C guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight FoldColumn guifg=#7C828D guibg=#0E1420 guisp=NONE blend=NONE gui=NONE
highlight Folded guifg=#C2C4C7 guibg=#5C6370 guisp=NONE blend=NONE gui=italic
highlight Function guifg=#7C828D guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Identifier guifg=#9096A2 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight IncSearch guifg=#5C6370 guibg=#6A707C guisp=NONE blend=NONE gui=NONE
highlight Include guifg=#7C828D guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Italic guifg=#C2C4C7 guibg=#0E1420 guisp=NONE blend=NONE gui=italic
highlight Keyword guifg=#BFB8C1 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Label guifg=#747A86 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight LineNr guifg=#9EA2A9 guibg=#0E1420 guisp=NONE blend=NONE gui=NONE
highlight Macro guifg=#5D636F guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight MatchParen guifg=#C2C4C7 guibg=#9EA2A9 guisp=NONE blend=NONE gui=NONE
highlight MiniCompletionActiveParameter guifg=NONE guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight MiniCursorword guifg=NONE guibg=NONE guisp=NONE blend=NONE gui=underline
highlight! link MiniCursorwordCurrent MiniCursorword
highlight MiniIndentscopePrefix guifg=NONE guibg=NONE guisp=NONE blend=NONE gui=nocombine
highlight MiniIndentscopeSymbol guifg=#5C6370 guibg=#0E1420 guisp=NONE blend=NONE gui=NONE
highlight MiniJump guifg=#7C828D guibg=NONE guisp=#9EA2A9 blend=NONE gui=underline
highlight MiniJump2dSpot guifg=NONE guibg=NONE guisp=NONE blend=NONE gui=undercurl
highlight MiniStarterCurrent guifg=NONE guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight MiniStarterFooter guifg=#7C828D guibg=NONE guisp=NONE blend=NONE gui=bold
highlight MiniStarterHeader guifg=#7C828D guibg=NONE guisp=NONE blend=NONE gui=bold
highlight MiniStarterInactive guifg=#C2C4C7 guibg=NONE guisp=NONE blend=NONE gui=italic
highlight MiniStarterItem guifg=#C2C4C7 guibg=#0E1420 guisp=NONE blend=NONE gui=NONE
highlight MiniStarterItemBullet guifg=#616875 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight MiniStarterItemPrefix guifg=#5D636F guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight MiniStarterQuery guifg=#676D79 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight MiniStarterSection guifg=#616875 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight MiniStatuslineDevinfo guifg=#C2C4C7 guibg=#5C6370 guisp=NONE blend=NONE gui=NONE
highlight MiniStatuslineFileinfo guifg=#C2C4C7 guibg=#5C6370 guisp=NONE blend=NONE gui=NONE
highlight MiniStatuslineFilename guifg=#747A86 guibg=#5C6370 guisp=NONE blend=NONE gui=NONE
highlight MiniStatuslineInactive guifg=#787F8C guibg=#5C6370 guisp=NONE blend=NONE gui=NONE
highlight MiniStatuslineModeCommand guifg=#0E1420 guibg=#9096A2 guisp=NONE blend=NONE gui=NONE
highlight MiniStatuslineModeInsert guifg=#0E1420 guibg=#7C828D guisp=NONE blend=NONE gui=NONE
highlight MiniStatuslineModeNormal guifg=#0E1420 guibg=#676D79 guisp=NONE blend=NONE gui=NONE
highlight MiniStatuslineModeOther guifg=#0E1420 guibg=#BFB8C1 guisp=NONE blend=NONE gui=NONE
highlight MiniStatuslineModeReplace guifg=#0E1420 guibg=#5D636F guisp=NONE blend=NONE gui=NONE
highlight MiniStatuslineModeVisual guifg=#0E1420 guibg=#6A707C guisp=NONE blend=NONE gui=NONE
highlight MiniSurround guifg=#5C6370 guibg=#6A707C guisp=NONE blend=NONE gui=NONE
highlight MiniTablineCurrent guifg=#9EA2A9 guibg=#5C6370 guisp=NONE blend=NONE gui=NONE
highlight MiniTablineFill guifg=NONE guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight MiniTablineHidden guifg=#676D79 guibg=#5C6370 guisp=NONE blend=NONE gui=NONE
highlight MiniTablineModifiedCurrent guifg=#C2C4C7 guibg=#5C6370 guisp=NONE blend=NONE gui=NONE
highlight MiniTablineModifiedHidden guifg=#787F8C guibg=#5C6370 guisp=NONE blend=NONE gui=NONE
highlight MiniTablineModifiedVisible guifg=#C2C4C7 guibg=#5C6370 guisp=NONE blend=NONE gui=NONE
highlight MiniTablineVisible guifg=#9EA2A9 guibg=#5C6370 guisp=NONE blend=NONE gui=NONE
highlight MiniTestEmphasis guifg=NONE guibg=NONE guisp=NONE blend=NONE gui=bold
highlight MiniTestFail guifg=NONE guibg=NONE guisp=NONE blend=NONE gui=bold
highlight MiniTestPass guifg=NONE guibg=NONE guisp=NONE blend=NONE gui=bold
highlight MiniTrailspace guifg=#5D636F guibg=#C2C4C7 guisp=NONE blend=NONE gui=NONE
highlight ModeMsg guifg=#676D79 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight MoreMsg guifg=#676D79 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight NonText guifg=#9EA2A9 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Number guifg=#6A707C guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Operator guifg=#C2C4C7 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight PMenu guifg=#C2C4C7 guibg=#5C6370 guisp=NONE blend=NONE gui=NONE
highlight PMenuSel guifg=#C2C4C7 guibg=#7C828D guisp=NONE blend=NONE gui=NONE
highlight PmenuSbar guifg=#787F8C guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight PmenuThumb guifg=#C2C4C7 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight PreProc guifg=#747A86 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Question guifg=#7C828D guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Repeat guifg=#747A86 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Search guifg=#9EA2A9 guibg=#747A86 guisp=NONE blend=NONE gui=NONE
highlight! link MiniTablineTabpagesection Search
highlight SignColumn guifg=#787F8C guibg=#0E1420 guisp=NONE blend=NONE gui=NONE
highlight Special guifg=#9096A2 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight SpecialChar guifg=#616875 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight SpecialKey guifg=#9EA2A9 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight SpellBad guifg=#5D636F guibg=NONE guisp=#5D636F blend=NONE gui=underline
highlight SpellCap guifg=#747A86 guibg=NONE guisp=#747A86 blend=NONE gui=underline
highlight SpellLocal guifg=#9096A2 guibg=NONE guisp=#9096A2 blend=NONE gui=underline
highlight SpellRare guifg=#BFB8C1 guibg=NONE guisp=#BFB8C1 blend=NONE gui=underline
highlight Statement guifg=#5D636F guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight StatusLine guifg=#C2C4C7 guibg=#5C6370 guisp=NONE blend=NONE gui=NONE
highlight StatusLineNC guifg=#787F8C guibg=#5C6370 guisp=NONE blend=NONE gui=NONE
highlight StatusLineTerm guifg=#676D79 guibg=#676D79 guisp=NONE blend=NONE gui=NONE
highlight StatusLineTermNC guifg=#747A86 guibg=#5C6370 guisp=NONE blend=NONE gui=NONE
highlight StorageClass guifg=#747A86 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight String guifg=#676D79 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Structure guifg=#BFB8C1 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight TabLine guifg=#9EA2A9 guibg=#5C6370 guisp=NONE blend=NONE gui=NONE
highlight TabLineFill guifg=#9EA2A9 guibg=#5C6370 guisp=NONE blend=NONE gui=NONE
highlight TabLineSel guifg=#676D79 guibg=#5C6370 guisp=NONE blend=NONE gui=NONE
highlight Tag guifg=#747A86 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Title guifg=#7C828D guibg=NONE guisp=NONE blend=NONE gui=bold
highlight Todo guifg=#747A86 guibg=#5C6370 guisp=NONE blend=NONE gui=NONE
highlight TooLong guifg=#5D636F guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Type guifg=#747A86 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Typedef guifg=#747A86 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Underlined guifg=#5D636F guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight VertSplit guifg=#C2C4C7 guibg=#0E1420 guisp=NONE blend=NONE gui=NONE
highlight! link WinSeparator VertSplit
highlight Visual guifg=#0E1420 guibg=#787F8C guisp=NONE blend=NONE gui=NONE
highlight VisualNOS guifg=#5D636F guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight WarningMsg guifg=#5D636F guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight WildMenu guifg=#C2C4C7 guibg=#7C828D guisp=NONE blend=NONE gui=NONE
highlight WinBar guifg=#C2C4C7 guibg=#0E1420 guisp=NONE blend=NONE gui=NONE
highlight WinBarNC guifg=#787F8C guibg=#0E1420 guisp=NONE blend=NONE gui=NONE
highlight gitCommitOverflow guifg=#5D636F guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight gitCommitSummary guifg=#676D79 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight helpCommand guifg=#747A86 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight helpExample guifg=#747A86 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @attribute guifg=#7C828D guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @boolean guifg=#7C828D guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @character guifg=#747A86 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @character.special guifg=#616875 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @comment guifg=#C2C4C7 guibg=NONE guisp=NONE blend=NONE gui=italic
highlight @conditional guifg=#5D636F guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @constant guifg=#5D636F guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @constant.builtin guifg=#5D636F guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @constant.macro guifg=#5D636F guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @constructor guifg=#C2C4C7 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @debug guifg=NONE guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @define guifg=#BFB8C1 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @exception guifg=#5D636F guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @field guifg=#676D79 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @float guifg=#7C828D guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @function guifg=#7C828D guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @function.builtin guifg=#5D636F guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @function.macro guifg=#5D636F guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @include guifg=#9096A2 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @keyword guifg=#BFB8C1 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @keyword.function guifg=#9096A2 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @keyword.operator guifg=#BFB8C1 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @label guifg=#9096A2 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @method guifg=#7C828D guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @namespace guifg=#7C828D guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @none guifg=NONE guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @number guifg=#7C828D guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @operator guifg=#C2C4C7 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @parameter guifg=#747A86 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @preproc guifg=#747A86 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @property guifg=#747A86 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @punctuation.bracket guifg=#C2C4C7 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @punctuation.delimiter guifg=#C2C4C7 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @punctuation.special guifg=#9096A2 guibg=NONE guisp=NONE blend=NONE gui=bold
highlight @repeat guifg=#5D636F guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @storageclass guifg=#747A86 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @string guifg=#7C828D guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @string.escape guifg=#676D79 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @string.regex guifg=#676D79 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @string.special guifg=#616875 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @symbol guifg=#9096A2 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @tag guifg=#747A86 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @tag.attribute guifg=#9096A2 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @tag.delimiter guifg=#9096A2 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @text guifg=#676D79 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @text.bold guifg=#747A86 guibg=NONE guisp=NONE blend=NONE gui=bold
highlight @text.danger guifg=#5D636F guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @text.diff.add guifg=#676D79 guibg=#5C6370 guisp=NONE blend=NONE gui=bold
highlight @text.diff.delete guifg=#5D636F guibg=#5C6370 guisp=NONE blend=NONE gui=bold
highlight @text.emphasis guifg=#BFB8C1 guibg=NONE guisp=NONE blend=NONE gui=italic
highlight @text.environment guifg=#5D636F guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @text.environment.name guifg=#747A86 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @text.literal guifg=#676D79 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @text.math guifg=#9096A2 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @text.note guifg=#9096A2 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @text.reference guifg=#5D636F guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @text.strike guifg=NONE guibg=NONE guisp=NONE blend=NONE gui=strikethrough
highlight @text.title guifg=#7C828D guibg=NONE guisp=NONE blend=NONE gui=bold
highlight @text.todo guifg=#747A86 guibg=#5C6370 guisp=NONE blend=NONE gui=NONE
highlight @text.underline guifg=NONE guibg=NONE guisp=NONE blend=NONE gui=underline
highlight @text.uri guifg=NONE guibg=#5C6370 guisp=NONE blend=NONE gui=underline
highlight @type guifg=#7C828D guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @type.builtin guifg=#7C828D guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @type.definition guifg=#747A86 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @variable guifg=#747A86 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @variable.builtin guifg=#5D636F guibg=NONE guisp=NONE blend=NONE gui=NONE
