# Window Settings
width=818
height=750
location=center
show=dmenu
prompt=Select wallpaper...
layer=overlay

# Layout
columns=3
image_size=250x141 # 16:9
allow_images=true
insensitive=true
hide_scroll=true
sort_order=default

# Style
style_path=~/.config/wofi/style.css
