#################
### AUTOSTART ###
#################

$terminal = kitty

xwayland {
  force_zero_scaling = true
}

exec-once = systemctl --user start hyprpolkitagent
exec-once = waybar
exec-once = nm-applet --indicator
exec-once = awww-daemon
exec-once = hypridle
exec-once = swaync
exec-once = $terminal
