
# Specifies monitor, resolution, refresh rate, and other information.
monitor = eDP-1, 1920x1080@59.93400, 0x0, 1

# Reserve monitor space for waybar, optional.
# monitor = eDP-1, addreserved, 45, 0, 0, 0
